services:
  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      PGVAULT_AGENT_URL: "http://host.docker.internal:9731"
    ports:
      - "8000:8000"
    networks:
      - pgstudio
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pgstudio
networks:
  pgstudio:
    driver: bridge
